## Working with Arrays

*Suggested Answers follow (usually there are multiple ways to solve a problem in Python).*

In [1]:
import numpy as np

In [2]:
a = np.array([[0, 1, 2, 3], [4, 5, 6, 7]])
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

Check the dimension you have created is correct (use “*.shape*”)

In [6]:
a.shape

(2L, 4L)

Substitute the 5th element from the 2nd row with 19.75.

In [3]:
a[1,4] = 19.75
a

NameError: name 'a' is not defined

Extract the 2nd and the 3rd row of the array you created. 

In [9]:
a[1]

array([0, 1, 2, 3])

In [10]:
a[2]

array([4, 5, 8, 7])