## Monte Carlo - Forecasting Stock Prices - Part II 

*Suggested Answers follow (usually there are multiple ways to solve a problem in Python).*

Forecasting Future Stock Prices – continued:

In [1]:
import numpy as np  
import pandas as pd  
from pandas_datareader import data as wb  
import matplotlib.pyplot as plt  
from scipy.stats import norm
%matplotlib inline

ticker = 'MSFT' 
data = pd.DataFrame()
data[ticker] = wb.DataReader(ticker, data_source='yahoo', start='2000-1-1')['Adj Close']

log_returns = np.log(1 + data.pct_change())
u = log_returns.mean()
var = log_returns.var()
drift = u - (0.5 * var)
stdev = log_returns.std()

******

Use “.values” to transform the *drift* and the *stdev* objects into arrays. 

In [2]:
type(drift)

pandas.core.series.Series

In [3]:
drift.values

array([7.46364383e-06])

In [4]:
type(stdev)

pandas.core.series.Series

In [5]:
stdev.values

array([0.01930022])

Forecast future stock prices for every trading day a year ahead. So, assign 250 to “t_intervals”. <br />
Let’s examine 10 possible outcomes. Bind “iterations” to the value of 10.

In [6]:
t_intervals = 250
iterations = 10

Use the formula we have provided and calculate daily returns.

$$
daily\_returns = exp({drift} + {stdev} * z), 
$$ 
<br \>
$$
where\  z = norm.ppf(np.random.rand(t\_intervals, iterations)
$$

In [7]:
daily_returns = np.exp(drift.values + stdev.values * norm.ppf(np.random.rand(t_intervals, iterations)))
daily_returns

array([[1.03593324, 0.98201404, 0.9512587 , ..., 0.99833944, 0.99036764,
        1.00301051],
       [0.95845553, 1.01475392, 0.97384285, ..., 0.99764094, 0.99019287,
        0.9994769 ],
       [1.00416107, 1.00460223, 0.98435686, ..., 1.00367427, 1.02363904,
        0.99906501],
       ...,
       [0.98905912, 0.99144493, 0.98486079, ..., 0.98607606, 1.02654412,
        1.01848441],
       [1.00445194, 0.99946385, 0.9995034 , ..., 1.01268564, 1.02079455,
        0.99631801],
       [1.03176323, 0.97845077, 0.98838881, ..., 0.97913083, 1.00724327,
        0.99147505]])