## Monte Carlo - Forecasting Stock Prices - Part II 

*Suggested Answers follow (usually there are multiple ways to solve a problem in Python).*

Forecasting Future Stock Prices – continued:

In [1]:
import numpy as np  
import pandas as pd  
from pandas_datareader import data as wb  
import matplotlib.pyplot as plt  
from scipy.stats import norm
%matplotlib inline

data = pd.read_csv('D:/Python/MSFT_2000.csv', index_col = 'Date')

log_returns = np.log(1 + data.pct_change())
u = log_returns.mean()
var = log_returns.var()
drift = u - (0.5 * var)
stdev = log_returns.std()

******

Use “.values” to transform the *drift* and the *stdev* objects into arrays. 

In [2]:
type(drift)

pandas.core.series.Series

In [3]:
drift.values

array([ -3.42521946e-05])

In [4]:
type(stdev)

pandas.core.series.Series

In [5]:
stdev.values

array([ 0.01939682])

Forecast future stock prices for every trading day a year ahead. So, assign 250 to “t_intervals”. <br />
Let’s examine 10 possible outcomes. Bind “iterations” to the value of 10.

In [6]:
t_intervals = 250
iterations = 10

Use the formula we have provided and calculate daily returns.

$$
daily\_returns = exp({drift} + {stdev} * z), 
$$ 
<br \>
$$
where\  z = norm.ppf(np.random.rand(t\_intervals, iterations)
$$

In [7]:
daily_returns = np.exp(drift.values + stdev.values * norm.ppf(np.random.rand(t_intervals, iterations)))
daily_returns

array([[ 1.04349   ,  1.01604234,  1.00293372, ...,  0.98887919,
         1.02431617,  1.00577522],
       [ 1.02119687,  0.98056692,  1.020506  , ...,  1.00942108,
         1.00105479,  1.00671925],
       [ 1.00294186,  0.98998804,  0.99562562, ...,  0.96918634,
         1.02265222,  1.01655192],
       ..., 
       [ 1.00159232,  0.99937562,  1.0216167 , ...,  0.98959137,
         0.99094284,  0.99479379],
       [ 1.0251291 ,  0.97836497,  0.97139958, ...,  1.04597457,
         1.0011809 ,  0.99421068],
       [ 0.99434018,  0.97163049,  0.97613251, ...,  1.00147267,
         0.98800248,  1.02204831]])